### PR TITLE
Add check in closes logic

### PR DESCRIPTION
**Pull request by keithbro**
Moving the logic of calculating check in closes dates to this library such that it can be shared with svc-order.

From here: https://github.com/lux-group/svc-public-offer/blob/master/src/utils/checkInCloses.js

To be used here: https://github.com/lux-group/svc-order/blob/master/src/context/accommodation/createReservation.js#L220

### CODE REVIEW

**Comment by zediah** [comment]
Adding knowledge of offer types here gives me the heeby jeebies. Especially as it’s a type exclusive to this at the moment.

maybw we can bring in lib types to provide the offer type type instead?

**Comment by keithbro** [comment]
> Adding knowledge of offer types here gives me the heeby jeebies. Especially as it’s a type exclusive to this at the moment.
> 
> maybw we can bring in lib types to provide the offer type type instead?

lib-types is for API types more than types that are internal to service/applications. I don't see much of a risk here to be honest since these change very infrequently. Also typescript's checking will ensure it stays in sync. It seems reasonable to me that a shared library for offers would know the different types of offers that are possible

**Comment by zediah** [comment]
> > Adding knowledge of offer types here gives me the heeby jeebies. Especially as it’s a type exclusive to this at the moment.
> > maybw we can bring in lib types to provide the offer type type instead?
> 
> lib-types is for API types more than types that are internal to service/applications. I don't see much of a risk here to be honest since these change very infrequently. Also typescript's checking will ensure it stays in sync. It seems reasonable to me that a shared library for offers would know the different types of offers that are possible

`OfferType` is basically a common enumeration being used across multiple repo's but defined individually in each one, that's what seems dangerous about letting yet another repo have it's own version.

Also `lib-types` should probably be named `lib-api-types` if that's the case as you describe

**Review by zediah — APPROVED** [review]

**Comment by keithbro** [comment]
> > > Adding knowledge of offer types here gives me the heeby jeebies. Especially as it’s a type exclusive to this at the moment.
> > > maybw we can bring in lib types to provide the offer type type instead?
> > 
> > 
> > lib-types is for API types more than types that are internal to service/applications. I don't see much of a risk here to be honest since these change very infrequently. Also typescript's checking will ensure it stays in sync. It seems reasonable to me that a shared library for offers would know the different types of offers that are possible
> 
> `OfferType` is basically a common enumeration being used across multiple repo's but defined individually in each one, that's what seems dangerous about letting yet another repo have it's own version.
> 
> Also `lib-types` should probably be named `lib-api-types` if that's the case as you describe

From the lib-types README: 

"API interfaces and factories for Luxury Escapes" and "Shareable API types for the REST endpoints"

I do think this is pretty safe - feel free to remind me of this PR if it turns out to be wrong.

**Pull request merged**
